name: Test

on:
  push:
    branches-ignore:
      - master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
      - name: Setup wasm-tools
        run: dotnet workload install wasm-experimental
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Build
        run: |
          make build
      - name: Test
        run: |
          make test
